Repository angelochristian29/Basilisk-Zero, pull requests merged in 2023-11, with the labels that each got.

#122 Saim branch
  Basilisk-Zero/Assets/Dialogues/Lvl15Tim.ink
  Basilisk-Zero/Assets/Dialogues/Lvl15Tim.ink.meta
  Basilisk-Zero/Assets/Dialogues/Lvl15Tim.json
  Basilisk-Zero/Assets/Dialogues/Lvl15Tim.json.meta
  Basilisk-Zero/Assets/Dialogues/Lvl15Walker.ink
  Basilisk-Zero/Assets/Dialogues/Lvl15Walker.ink.meta
  Basilisk-Zero/Assets/Dialogues/Lvl15Walker.json
  Basilisk-Zero/Assets/Dialogues/Lvl15Walker.json.meta
  Basilisk-Zero/Assets/Dialogues/Sensors_Dialouge.ink
  Basilisk-Zero/Assets/Dialogues/Sensors_Dialouge.ink.meta
  Basilisk-Zero/Assets/Dialogues/Sensors_Dialouge.json
  Basilisk-Zero/Assets/Dialogues/Sensors_Dialouge.json.meta
  Basilisk-Zero/Assets/Dialogues/npcDialogue.ink
  Basilisk-Zero/Assets/Dialogues/npcDialogue.json
  Basilisk-Zero/Assets/Prefabs/NPC/Zach/Zach 1.prefab
  Basilisk-Zero/Assets/Prefabs/NPC/Zach/Zach 1.prefab.meta
  Basilisk-Zero/Assets/Prefabs/NPC/lvl15.meta
  Basilisk-Zero/Assets/Prefabs/NPC/lvl15/Tim Variant.prefab
  Basilisk-Zero/Assets/Prefabs/NPC/lvl15/Tim Variant.prefab.meta
  Basilisk-Zero/Assets/Prefabs/NPC/lvl15/WalkingWorker1 Variant.prefab
  Basilisk-Zero/Assets/Prefabs/NPC/lvl15/WalkingWorker1 Variant.prefab.meta
  Basilisk-Zero/Assets/Resources/sensors.txt
  Basilisk-Zero/Assets/Resources/sensors.txt.meta
  Basilisk-Zero/Assets/Scenes/FifteenthFloor.unity
  Basilisk-Zero/Assets/Scenes/FirstFloor.unity
  Basilisk-Zero/Assets/Scripts/MiniGame/OpenTypingGame.cs
  Basilisk-Zero/Assets/script.cs
  Basilisk-Zero/Assets/script.cs.meta
  Basilisk-Zero/UserSettings/EditorUserSettings.asset
  Basilisk-Zero/UserSettings/Layouts/CurrentMaximizeLayout.dwlt
  Basilisk-Zero/UserSettings/Layouts/default-2021.dwlt
Labels: bug, enhancement, prototype

#123 Npc main merge 2
  .gitignore
  Basilisk-Zero/Assets/ArtTemplate/Items/Materials.meta
  Basilisk-Zero/Assets/ArtTemplate/Items/Materials/credit_card_1.mat
  Basilisk-Zero/Assets/ArtTemplate/Items/Materials/credit_card_1.mat.meta
  Basilisk-Zero/Assets/Dialogues/GuardDialogue.ink
  Basilisk-Zero/Assets/Dialogues/GuardDialogue.ink.meta
  Basilisk-Zero/Assets/Dialogues/GuardDialogue.json
  Basilisk-Zero/Assets/Dialogues/GuardDialogue.json.meta
  Basilisk-Zero/Assets/Dialogues/npcDialogue.ink
  Basilisk-Zero/Assets/Dialogues/npcDialogue.json
  Basilisk-Zero/Assets/Prefabs/Computers.meta
  Basilisk-Zero/Assets/Prefabs/Computers/DerailmentPC.prefab
  Basilisk-Zero/Assets/Prefabs/Computers/DerailmentPC.prefab.meta
  Basilisk-Zero/Assets/Prefabs/Computers/SupportAIPC.prefab
  Basilisk-Zero/Assets/Prefabs/Computers/SupportAIPC.prefab.meta
  Basilisk-Zero/Assets/Prefabs/NPC/Nico.meta
  Basilisk-Zero/Assets/Prefabs/NPC/Nico/nico Variant.prefab
  Basilisk-Zero/Assets/Prefabs/NPC/Nico/nico Variant.prefab.meta
  Basilisk-Zero/Assets/Scenes/FirstFloor.unity
  Basilisk-Zero/Assets/Scenes/SecondFloor.unity
  Basilisk-Zero/Assets/Scenes/TwentyEighthFloor.unity
  Basilisk-Zero/Assets/Scripts/AreaEnter.cs
  Basilisk-Zero/Assets/Scripts/Dialogue/InkDialogueManager.cs
  Basilisk-Zero/Assets/Scripts/Dialogue/InkDialogueTrigger.cs
  Basilisk-Zero/Assets/Scripts/Dialogue/InkExternalFunctions.cs
  Basilisk-Zero/Assets/Scripts/NpcManagement.meta
  Basilisk-Zero/Assets/Scripts/NpcManagement/GuardMovement.cs
  Basilisk-Zero/Assets/Scripts/NpcManagement/GuardMovement.cs.meta
  Basilisk-Zero/Assets/Scripts/NpcManagement/INPC.cs
  Basilisk-Zero/Assets/Scripts/NpcManagement/INPC.cs.meta
  Basilisk-Zero/Assets/Scripts/NpcManagement/NPCMovement.cs
  Basilisk-Zero/Assets/Scripts/NpcManagement/NPCMovement.cs.meta
  Basilisk-Zero/Assets/Scripts/NpcManagement/Npc.cs
  Basilisk-Zero/Assets/Scripts/NpcManagement/Npc.cs.meta
  Basilisk-Zero/Assets/Scripts/NpcManagement/NpcCutscene.cs
  Basilisk-Zero/Assets/Scripts/NpcManagement/NpcCutscene.cs.meta
  Basilisk-Zero/Assets/Scripts/PlayerController.cs
  Basilisk-Zero/UserSettings/Layouts/default-2021.dwlt
Labels: enhancement, prototype, in-progress

#126 Merge Saim branch to second floor fixes
  Basilisk-Zero/Assets/Dialogues/DawnDialogue.json
  Basilisk-Zero/Assets/Dialogues/ElevatorLevelSelect.json
  Basilisk-Zero/Assets/Dialogues/Lvl15Tim.json
  Basilisk-Zero/Assets/Dialogues/Lvl15Walker.ink
  Basilisk-Zero/Assets/Dialogues/Lvl15Walker.json
  Basilisk-Zero/Assets/Dialogues/NicoGreeting.json
  Basilisk-Zero/Assets/Dialogues/ReceptionistGreetings.json
  Basilisk-Zero/Assets/Dialogues/Sensors_Dialouge.ink
  Basilisk-Zero/Assets/Dialogues/Sensors_Dialouge.json
  Basilisk-Zero/Assets/Dialogues/ZachDialogue.ink
  Basilisk-Zero/Assets/Dialogues/ZachDialogue.json
  Basilisk-Zero/Assets/Dialogues/globals.ink
  Basilisk-Zero/Assets/Dialogues/load_globals.json
  Basilisk-Zero/Assets/Dialogues/npcDialogue.json
  Basilisk-Zero/Assets/Scenes/FifteenthFloor.unity
  Basilisk-Zero/UserSettings/EditorUserSettings.asset
  Basilisk-Zero/UserSettings/Layouts/CurrentMaximizeLayout.dwlt
Labels: enhancement, prototype

#129 28th floor bugfixes haroon to 2nd floor bug fixes
  Basilisk-Zero/.plastic/plastic.changes
  Basilisk-Zero/.plastic/plastic.selector
  Basilisk-Zero/.plastic/plastic.wktree
  Basilisk-Zero/.plastic/plastic.workspace
  Basilisk-Zero/Assets/Scenes/FirstFloor.unity
  Basilisk-Zero/Assets/Scenes/TwentyEighthFloor.unity
  Basilisk-Zero/Assets/Scripts/NpcManagement/NpcCutscene.cs
  Basilisk-Zero/Packages/manifest.json
  Basilisk-Zero/Packages/packages-lock.json
  Basilisk-Zero/ProjectSettings/TagManager.asset
  Basilisk-Zero/UserSettings/EditorUserSettings.asset
  Basilisk-Zero/UserSettings/Layouts/CurrentMaximizeLayout.dwlt
  Basilisk-Zero/UserSettings/Layouts/default-2021.dwlt
  Basilisk-Zero/ignore.conf
Labels: enhancement, prototype

#131 Fix story bugs 2 floor
  Basilisk-Zero/Assets/ArtTemplate/tiles/Materials.meta
  Basilisk-Zero/Assets/ArtTemplate/tiles/Materials/computer_desk.mat
  Basilisk-Zero/Assets/ArtTemplate/tiles/Materials/computer_desk.mat.meta
  Basilisk-Zero/Assets/Dialogues/CEODialogue.ink
  Basilisk-Zero/Assets/Dialogues/CEODialogue.json
  Basilisk-Zero/Assets/Dialogues/ComputerDialogue.ink
  Basilisk-Zero/Assets/Dialogues/ComputerDialogue.ink.meta
  Basilisk-Zero/Assets/Dialogues/ComputerDialogue.json
  Basilisk-Zero/Assets/Dialogues/ComputerDialogue.json.meta
  Basilisk-Zero/Assets/Dialogues/DawnDialogue.ink
  Basilisk-Zero/Assets/Dialogues/DawnDialogue.json
  Basilisk-Zero/Assets/Dialogues/ElevatorLevelSelect.ink
  Basilisk-Zero/Assets/Dialogues/ElevatorLevelSelect.json
  Basilisk-Zero/Assets/Dialogues/NicoGreeting.ink
  Basilisk-Zero/Assets/Dialogues/NicoGreeting.json
  Basilisk-Zero/Assets/Dialogues/ReceptionistGreetings.ink
  Basilisk-Zero/Assets/Dialogues/ZachDialogue.ink
  Basilisk-Zero/Assets/Dialogues/ZachDialogue.json
  Basilisk-Zero/Assets/Dialogues/npcDialogue.ink
  Basilisk-Zero/Assets/Dialogues/npcDialogue.json
  Basilisk-Zero/Assets/Scenes/FirstFloor.unity
  Basilisk-Zero/Assets/Scenes/SecondFloor.unity
  Basilisk-Zero/UserSettings/EditorUserSettings.asset
  Basilisk-Zero/UserSettings/Layouts/default-2021.dwlt
Labels: enhancement, prototype

#136 Updated story and art assets
  Basilisk-Zero/Assets/ArtTemplate/NPC/No Outlines/NPC_1-4.png
  Basilisk-Zero/Assets/ArtTemplate/NPC/No Outlines/NPC_1-4.png.meta
  Basilisk-Zero/Assets/ArtTemplate/Players/No Outlines/mc_run.png
  Basilisk-Zero/Assets/ArtTemplate/Players/No Outlines/mc_run.png.meta
  Basilisk-Zero/Assets/Dialogues/CEODialogue.ink
  Basilisk-Zero/Assets/Dialogues/CEODialogue.json
  Basilisk-Zero/Assets/Dialogues/ComputerDialogue.ink
  Basilisk-Zero/Assets/Dialogues/ComputerDialogue.json
  Basilisk-Zero/Assets/Dialogues/Lvl15Walker.ink
  Basilisk-Zero/Assets/Dialogues/Lvl15Walker.json
  Basilisk-Zero/Assets/Dialogues/Sensors_Dialouge.ink
  Basilisk-Zero/Assets/Dialogues/Sensors_Dialouge.json
  Basilisk-Zero/Assets/Dialogues/ZachDialogue.ink
  Basilisk-Zero/Assets/Dialogues/ZachDialogue.json
  Basilisk-Zero/Assets/Prefabs/Player/Animations/player_idle.anim
  Basilisk-Zero/Assets/Prefabs/Player/Animations/player_run.anim
  Basilisk-Zero/Assets/Prefabs/Player/Player_AC.controller
  Basilisk-Zero/Assets/Scenes/FifteenthFloor.unity
  Basilisk-Zero/Assets/Scenes/FirstFloor.unity
  Basilisk-Zero/Assets/Scenes/SecondFloor.unity
  Basilisk-Zero/UserSettings/EditorUserSettings.asset
  Basilisk-Zero/UserSettings/Layouts/default-2021.dwlt
Labels: enhancement

#140 Added ending dialogue for CEO
  Basilisk-Zero/Assets/Dialogues/CEODialogue.ink
  Basilisk-Zero/Assets/Dialogues/CEODialogue.json
  Basilisk-Zero/Assets/Dialogues/ElevatorLevelSelect.ink
  Basilisk-Zero/Assets/Dialogues/ElevatorLevelSelect.json
  Basilisk-Zero/Assets/Dialogues/Sensors_Dialouge.ink
  Basilisk-Zero/Assets/Dialogues/Sensors_Dialouge.json
  Basilisk-Zero/Assets/Dialogues/npcDialogue.ink
  Basilisk-Zero/Assets/Dialogues/npcDialogue.json
  Basilisk-Zero/Assets/Prefabs/NPC/CEO/CEO.prefab
  Basilisk-Zero/Assets/Scenes/SeventySecondFloor.unity
  Basilisk-Zero/UserSettings/EditorUserSettings.asset
  Basilisk-Zero/UserSettings/Layouts/default-2021.dwlt
Labels: enhancement, prototype
